
    CREATE TABLE ASSOCIADO (
       ID UUID NOT NULL,
        NOME VARCHAR(255),
        PRIMARY KEY (ID)
    );

    CREATE TABLE PAUTA (
       ID UUID NOT NULL,
        DESCRICAO VARCHAR(255),
        NOME VARCHAR(255),
        PRIMARY KEY (ID)
    );

    CREATE TABLE SESSAO_VOTACAO (
       ID UUID NOT NULL,
        MOMENTO_INICIO TIMESTAMP(6),
        STATUS SMALLINT,
        TEMPO_VOTACAO_IN_MINUTES INTEGER NOT NULL,
        PAUTA_ID UUID,
        PRIMARY KEY (ID)
    );

    CREATE TABLE VOTO (
       ID UUID NOT NULL,
        MOMENTO_VOTO TIMESTAMP(6),
        OPCAO SMALLINT,
        ASSOCIADO_ID UUID,
        SESSAO_VOTACAO_ID UUID,
        PRIMARY KEY (ID)
    );

    ALTER TABLE IF EXISTS SESSAO_VOTACAO
       ADD CONSTRAINT FK_PAUTA
       FOREIGN KEY (PAUTA_ID)
       REFERENCES PAUTA;

    ALTER TABLE IF EXISTS VOTO
       ADD CONSTRAINT FK_ASSOCIADO
       FOREIGN KEY (ASSOCIADO_ID)
       REFERENCES ASSOCIADO;

    ALTER TABLE IF EXISTS VOTO
       ADD CONSTRAINT FK_SESSAO_VOTACAO
       FOREIGN KEY (SESSAO_VOTACAO_ID)
       REFERENCES SESSAO_VOTACAO;
